{% set name = "napari-splineit" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_splineit-{{ version }}.tar.gz
  sha256: 85c6a1c8aa43c85e4b2f0770e51494f691d99475df234f4ba20db3324bcbe84b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari
    - numpy
    - python >=3.7
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_splineit
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uhlmanngroup/napari-splineit
  summary: A napari plugin for spline manipulation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
    - goanpeca
    - jaimergp
