{% set name = "napari-splineit" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_splineit-{{ version }}.tar.gz
  sha256: 5b12e91a8db8e044e612fb761f5129ac20547c106aba16026320437a53ce3d78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari
    - numpy
    - python >=3.7
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_splineit
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uhlmanngroup/napari-splineit
  summary: A napari plugin for spline manipulation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
    - goanpeca
    - jaimergp
